[2022-09-15 15:42:23,494] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: preprocessing_data.validate_model scheduled__2022-09-15T14:57:39.170269+00:00 [queued]>
[2022-09-15 15:42:23,499] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: preprocessing_data.validate_model scheduled__2022-09-15T14:57:39.170269+00:00 [queued]>
[2022-09-15 15:42:23,499] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-09-15 15:42:23,499] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-09-15 15:42:23,499] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-09-15 15:42:23,515] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): validate_model> on 2022-09-15 14:57:39.170269+00:00
[2022-09-15 15:42:23,521] {standard_task_runner.py:52} INFO - Started process 46390 to run task
[2022-09-15 15:42:23,526] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'preprocessing_data', 'validate_model', 'scheduled__2022-09-15T14:57:39.170269+00:00', '--job-id', '261', '--raw', '--subdir', 'DAGS_FOLDER/model_dag.py', '--cfg-path', '/tmp/tmp3d4jy_o8', '--error-file', '/tmp/tmpf85aqs7e']
[2022-09-15 15:42:23,526] {standard_task_runner.py:80} INFO - Job 261: Subtask validate_model
[2022-09-15 15:42:23,576] {task_command.py:371} INFO - Running <TaskInstance: preprocessing_data.validate_model scheduled__2022-09-15T14:57:39.170269+00:00 [running]> on host rc1b-dataproc-m-xzxwmqcudfo0foh0.mdb.yandexcloud.net
[2022-09-15 15:42:23,625] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=preprocessing_data
AIRFLOW_CTX_TASK_ID=validate_model
AIRFLOW_CTX_EXECUTION_DATE=2022-09-15T14:57:39.170269+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-15T14:57:39.170269+00:00
[2022-09-15 15:42:37,827] {logging_mixin.py:115} WARNING - 2022/09/15 15:42:37 INFO mlflow.spark: 'runs:/9dff32f633e04bafaa58b66628dcb5e6/model' resolved as 's3://otus-bigdata-dima-ioksha/1/9dff32f633e04bafaa58b66628dcb5e6/artifacts/model'
[2022-09-15 15:42:37,903] {credentials.py:1094} INFO - Found credentials in environment variables.
[2022-09-15 15:42:38,593] {logging_mixin.py:115} WARNING - 2022/09/15 15:42:38 INFO mlflow.spark: URI 's3://otus-bigdata-dima-ioksha/1/9dff32f633e04bafaa58b66628dcb5e6/artifacts/model/sparkml' does not point to the current DFS.
[2022-09-15 15:42:38,593] {logging_mixin.py:115} WARNING - 2022/09/15 15:42:38 INFO mlflow.spark: File 's3://otus-bigdata-dima-ioksha/1/9dff32f633e04bafaa58b66628dcb5e6/artifacts/model/sparkml' not found on DFS. Will attempt to upload the file.
[2022-09-15 15:42:39,233] {logging_mixin.py:115} WARNING - 2022/09/15 15:42:39 INFO mlflow.spark: Copied SparkML model to /tmp/mlflow/b395f4f6-a39b-4250-8af2-90873c92c6ff
[2022-09-15 15:42:46,103] {logging_mixin.py:115} WARNING - 2022/09/15 15:42:46 INFO mlflow.spark: 'runs:/9dff32f633e04bafaa58b66628dcb5e6/pipeline' resolved as 's3://otus-bigdata-dima-ioksha/1/9dff32f633e04bafaa58b66628dcb5e6/artifacts/pipeline'
[2022-09-15 15:42:46,615] {logging_mixin.py:115} WARNING - 2022/09/15 15:42:46 INFO mlflow.spark: URI 's3://otus-bigdata-dima-ioksha/1/9dff32f633e04bafaa58b66628dcb5e6/artifacts/pipeline/sparkml' does not point to the current DFS.
[2022-09-15 15:42:46,615] {logging_mixin.py:115} WARNING - 2022/09/15 15:42:46 INFO mlflow.spark: File 's3://otus-bigdata-dima-ioksha/1/9dff32f633e04bafaa58b66628dcb5e6/artifacts/pipeline/sparkml' not found on DFS. Will attempt to upload the file.
[2022-09-15 15:42:47,251] {logging_mixin.py:115} WARNING - 2022/09/15 15:42:47 INFO mlflow.spark: Copied SparkML model to /tmp/mlflow/d69aa605-f76a-43f5-9c94-1a496c0085fa
[2022-09-15 15:42:52,911] {validate_model.py:48} INFO - CURRENT_ROC_AUC: 0.5986627937539882
[2022-09-15 15:42:52,912] {python.py:173} INFO - Done. Returned value was: None
[2022-09-15 15:42:52,924] {taskinstance.py:1415} INFO - Marking task as SUCCESS. dag_id=preprocessing_data, task_id=validate_model, execution_date=20220915T145739, start_date=20220915T154223, end_date=20220915T154252
[2022-09-15 15:42:52,986] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-15 15:42:52,996] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
