[2022-09-05 12:43:00,446] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: preprocessing_data.fit_model scheduled__2022-09-05T12:07:28.970860+00:00 [queued]>
[2022-09-05 12:43:00,452] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: preprocessing_data.fit_model scheduled__2022-09-05T12:07:28.970860+00:00 [queued]>
[2022-09-05 12:43:00,452] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 12:43:00,452] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-09-05 12:43:00,452] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-09-05 12:43:00,474] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): fit_model> on 2022-09-05 12:07:28.970860+00:00
[2022-09-05 12:43:00,481] {standard_task_runner.py:52} INFO - Started process 38060 to run task
[2022-09-05 12:43:00,484] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'preprocessing_data', 'fit_model', 'scheduled__2022-09-05T12:07:28.970860+00:00', '--job-id', '141', '--raw', '--subdir', 'DAGS_FOLDER/model_dag.py', '--cfg-path', '/tmp/tmp14vyox8j', '--error-file', '/tmp/tmp705ltc_a']
[2022-09-05 12:43:00,485] {standard_task_runner.py:80} INFO - Job 141: Subtask fit_model
[2022-09-05 12:43:00,538] {task_command.py:371} INFO - Running <TaskInstance: preprocessing_data.fit_model scheduled__2022-09-05T12:07:28.970860+00:00 [running]> on host rc1b-dataproc-m-xzxwmqcudfo0foh0.mdb.yandexcloud.net
[2022-09-05 12:43:00,602] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=preprocessing_data
AIRFLOW_CTX_TASK_ID=fit_model
AIRFLOW_CTX_EXECUTION_DATE=2022-09-05T12:07:28.970860+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-05T12:07:28.970860+00:00
[2022-09-05 12:43:00,604] {train_model.py:37} INFO - GOT INTO TRAIN FUNCTION
[2022-09-05 12:43:00,609] {train_model.py:41} INFO - Data path: /user/airflow/processed_files/partition_48.parquet
[2022-09-05 12:43:48,950] {logging_mixin.py:115} WARNING - 2022/09/05 12:43:48 WARNING mlflow.pyspark.ml: Model inputs contain unsupported Spark data types: [StructField(featuresFinal,VectorUDT,true)]. Model signature is not logged.
[2022-09-05 12:44:04,925] {credentials.py:1094} INFO - Found credentials in environment variables.
[2022-09-05 12:44:24,769] {train_model.py:70} INFO - Accuracy SCORE: 0.5
[2022-09-05 12:44:24,801] {python.py:173} INFO - Done. Returned value was: None
[2022-09-05 12:44:24,810] {taskinstance.py:1415} INFO - Marking task as SUCCESS. dag_id=preprocessing_data, task_id=fit_model, execution_date=20220905T120728, start_date=20220905T124300, end_date=20220905T124424
[2022-09-05 12:44:24,868] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-05 12:44:24,882] {local_task_job.py:273} INFO - 0 downstream tasks scheduled from follow-on schedule check
