[2022-09-16 14:21:12,443] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: preprocessing_data.fit_model scheduled__2022-09-16T14:08:35.443508+00:00 [queued]>
[2022-09-16 14:21:12,448] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: preprocessing_data.fit_model scheduled__2022-09-16T14:08:35.443508+00:00 [queued]>
[2022-09-16 14:21:12,449] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-09-16 14:21:12,449] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-09-16 14:21:12,449] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-09-16 14:21:12,464] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): fit_model> on 2022-09-16 14:08:35.443508+00:00
[2022-09-16 14:21:12,471] {standard_task_runner.py:52} INFO - Started process 93846 to run task
[2022-09-16 14:21:12,476] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'preprocessing_data', 'fit_model', 'scheduled__2022-09-16T14:08:35.443508+00:00', '--job-id', '387', '--raw', '--subdir', 'DAGS_FOLDER/model_dag.py', '--cfg-path', '/tmp/tmppym0b3x1', '--error-file', '/tmp/tmpjofwww3i']
[2022-09-16 14:21:12,476] {standard_task_runner.py:80} INFO - Job 387: Subtask fit_model
[2022-09-16 14:21:12,529] {task_command.py:371} INFO - Running <TaskInstance: preprocessing_data.fit_model scheduled__2022-09-16T14:08:35.443508+00:00 [running]> on host rc1b-dataproc-m-xzxwmqcudfo0foh0.mdb.yandexcloud.net
[2022-09-16 14:21:12,586] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=preprocessing_data
AIRFLOW_CTX_TASK_ID=fit_model
AIRFLOW_CTX_EXECUTION_DATE=2022-09-16T14:08:35.443508+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-16T14:08:35.443508+00:00
[2022-09-16 14:21:12,587] {train_model.py:37} INFO - GOT INTO TRAIN FUNCTION
[2022-09-16 14:21:12,595] {train_model.py:42} INFO - Data path: /user/airflow/processed_files/slice_of_82_92.parquet
[2022-09-16 14:23:05,116] {logging_mixin.py:115} WARNING - 2022/09/16 14:23:05 WARNING mlflow.pyspark.ml: Model inputs contain unsupported Spark data types: [StructField(featuresFinal,VectorUDT,true)]. Model signature is not logged.
[2022-09-16 14:23:23,053] {credentials.py:1094} INFO - Found credentials in environment variables.
[2022-09-16 14:23:36,372] {train_model.py:71} INFO - Accuracy SCORE: 0.6119285223093459
[2022-09-16 14:23:36,404] {python.py:173} INFO - Done. Returned value was: None
[2022-09-16 14:23:36,415] {taskinstance.py:1415} INFO - Marking task as SUCCESS. dag_id=preprocessing_data, task_id=fit_model, execution_date=20220916T140835, start_date=20220916T142112, end_date=20220916T142336
[2022-09-16 14:23:36,449] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-16 14:23:36,470] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
