[2022-09-15 15:50:29,385] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: preprocessing_data.fit_model scheduled__2022-09-15T15:32:53.618883+00:00 [queued]>
[2022-09-15 15:50:29,390] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: preprocessing_data.fit_model scheduled__2022-09-15T15:32:53.618883+00:00 [queued]>
[2022-09-15 15:50:29,390] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-09-15 15:50:29,390] {taskinstance.py:1377} INFO - Starting attempt 1 of 2
[2022-09-15 15:50:29,390] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-09-15 15:50:29,404] {taskinstance.py:1397} INFO - Executing <Task(PythonOperator): fit_model> on 2022-09-15 15:32:53.618883+00:00
[2022-09-15 15:50:29,410] {standard_task_runner.py:52} INFO - Started process 50242 to run task
[2022-09-15 15:50:29,413] {standard_task_runner.py:79} INFO - Running: ['airflow', 'tasks', 'run', 'preprocessing_data', 'fit_model', 'scheduled__2022-09-15T15:32:53.618883+00:00', '--job-id', '269', '--raw', '--subdir', 'DAGS_FOLDER/model_dag.py', '--cfg-path', '/tmp/tmpbmurc0gm', '--error-file', '/tmp/tmpjqpvch15']
[2022-09-15 15:50:29,414] {standard_task_runner.py:80} INFO - Job 269: Subtask fit_model
[2022-09-15 15:50:29,459] {task_command.py:371} INFO - Running <TaskInstance: preprocessing_data.fit_model scheduled__2022-09-15T15:32:53.618883+00:00 [running]> on host rc1b-dataproc-m-xzxwmqcudfo0foh0.mdb.yandexcloud.net
[2022-09-15 15:50:29,506] {taskinstance.py:1589} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=airflow@example.com
AIRFLOW_CTX_DAG_OWNER=airflow
AIRFLOW_CTX_DAG_ID=preprocessing_data
AIRFLOW_CTX_TASK_ID=fit_model
AIRFLOW_CTX_EXECUTION_DATE=2022-09-15T15:32:53.618883+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-09-15T15:32:53.618883+00:00
[2022-09-15 15:50:29,507] {train_model.py:37} INFO - GOT INTO TRAIN FUNCTION
[2022-09-15 15:50:29,514] {train_model.py:42} INFO - Data path: /user/airflow/processed_files/slice_of_63_73.parquet
[2022-09-15 15:52:21,050] {logging_mixin.py:115} WARNING - 2022/09/15 15:52:21 WARNING mlflow.pyspark.ml: Model inputs contain unsupported Spark data types: [StructField(featuresFinal,VectorUDT,true)]. Model signature is not logged.
[2022-09-15 15:52:37,779] {credentials.py:1094} INFO - Found credentials in environment variables.
[2022-09-15 15:52:50,482] {train_model.py:71} INFO - Accuracy SCORE: 0.6176882724205358
[2022-09-15 15:52:50,511] {python.py:173} INFO - Done. Returned value was: None
[2022-09-15 15:52:50,520] {taskinstance.py:1415} INFO - Marking task as SUCCESS. dag_id=preprocessing_data, task_id=fit_model, execution_date=20220915T153253, start_date=20220915T155029, end_date=20220915T155250
[2022-09-15 15:52:50,563] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-09-15 15:52:50,584] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
